import {
  Agency,
  ProviderUser,
  Referral,
  ReferralOutcomeUpdate,
  RevenueSubmission,
  SupportThread,
  AuditEvent,
  DocumentFile,
} from './types'

// ---------------------------------------------------------------------------
// MOCK SEED DATA
// Fixed ISO timestamps (no `new Date()` / `Date.now()` at module scope) so the
// server and client render identical output — avoids React hydration mismatch.
// All records carry an `agencyId` so the mock data-access layer can enforce
// strict tenant isolation (see src/lib/api.ts).
// ---------------------------------------------------------------------------

// ---- Agencies -------------------------------------------------------------

export const mockAgency: Agency = {
  id: 'agency-101',
  legalName: 'Compassionate Bay Care LLC',
  displayName: 'Compassionate Bay Care',
  status: 'Active',
  serviceOfferings: ['Companion Care', 'Memory Care'],
  rates: { hourly: 35, onCall: 50, overnight: 40, weekend: 45 },
  liveInCareOffered: true,
  depositRequired: false,
  paymentMethods: ['Autopay', 'Credit Card', 'ACH'],
  availability: '24/7',
  serviceAreas: ['94105', '94107', '94110'],
  languages: ['English', 'Spanish'],
  caregiverScreeningStatus: 'Background Checked & Fingerprinted',
  certificationLevels: ['HHA', 'CNA'],
  profileDescription: 'Providing quality home care in the Bay Area.',
  logoFileId: undefined,
  photoFileIds: [],
  contactInfo: {
    phone: '(555) 123-4567',
    email: 'intake@cbcare.mock',
    address: '123 Main St, SF, CA',
    businessHours: 'Mon-Fri 9am-5pm',
  },
  profileCompleteness: 85,
  lastVerifiedAt: '2026-05-30T16:20:00.000Z',
  lastVerifiedBy: 'Sarah Intake',
  activationStatus: 'Active',
  agreements: { businessLicense: true, referralAgreement: true, baa: true },
}

const secondAgency: Agency = {
  id: 'agency-202',
  legalName: 'Golden Gate Senior Care Inc.',
  displayName: 'Golden Gate Senior Care',
  status: 'Active',
  serviceOfferings: ['Home Care', 'Skilled Nursing', 'Respite Care'],
  rates: { hourly: 38, onCall: 55, overnight: 44, weekend: 48 },
  liveInCareOffered: false,
  depositRequired: true,
  paymentMethods: ['Credit Card', 'ACH'],
  availability: 'Mon-Sun 6am-10pm',
  serviceAreas: ['94601', '94602', '94603'],
  languages: ['English', 'Cantonese', 'Tagalog'],
  caregiverScreeningStatus: 'Background Checked',
  certificationLevels: ['CNA', 'LVN'],
  profileDescription: 'Skilled and compassionate care across the East Bay.',
  photoFileIds: [],
  contactInfo: {
    phone: '(555) 987-6543',
    email: 'office@ggsc.mock',
    address: '900 Broadway, Oakland, CA',
    businessHours: 'Mon-Sun 6am-10pm',
  },
  profileCompleteness: 72,
  activationStatus: 'Pending Activation',
  agreements: { businessLicense: true, referralAgreement: false, baa: false },
}

export const mockAgencies: Agency[] = [mockAgency, secondAgency]

// ---- Provider users -------------------------------------------------------

export const mockUser: ProviderUser = {
  id: 'user-001',
  agencyId: 'agency-101',
  name: 'Sarah Intake',
  email: 'sarah@cbcare.mock',
  role: 'Provider Intake Coordinator',
  status: 'Active',
  lastLoginAt: '2026-06-28T13:05:00.000Z',
  mfaEnabled: true,
}

export const mockUsers: ProviderUser[] = [
  mockUser,
  {
    id: 'user-002',
    agencyId: 'agency-101',
    name: 'David Owner',
    email: 'david@cbcare.mock',
    role: 'Provider Owner',
    status: 'Active',
    lastLoginAt: '2026-06-27T22:41:00.000Z',
    mfaEnabled: true,
  },
  {
    id: 'user-003',
    agencyId: 'agency-101',
    name: 'Priya Billing',
    email: 'priya@cbcare.mock',
    role: 'Provider Billing',
    status: 'Active',
    lastLoginAt: '2026-06-26T18:10:00.000Z',
    mfaEnabled: false,
  },
  {
    id: 'admin-001',
    agencyId: 'agency-101',
    name: 'FindAHomeCare Admin',
    email: 'admin@findahomecare.mock',
    role: 'Internal Admin',
    status: 'Active',
    lastLoginAt: '2026-06-28T09:00:00.000Z',
    mfaEnabled: true,
  },
  {
    id: 'audit-001',
    agencyId: 'agency-101',
    name: 'Compliance Auditor',
    email: 'audit@findahomecare.mock',
    role: 'Internal Compliance/Audit',
    status: 'Active',
    lastLoginAt: '2026-06-28T08:30:00.000Z',
    mfaEnabled: true,
  },
]

// ---- Referrals ------------------------------------------------------------

export const mockReferrals: Referral[] = [
  {
    id: 'ref-100',
    agencyId: 'agency-101',
    inquiryFor: 'Parent',
    firstNameMasked: 'M***',
    lastNameMasked: 'G********',
    fullNameEncrypted: 'Maria Gonzallez',
    emailMasked: 'm***@example.com',
    phoneMasked: '(555) ***-**67',
    category: 'Companion Care',
    locationZip: '94105',
    message: 'Looking for 3 days a week.',
    status: 'New',
    assignmentDate: '2026-06-27T17:30:00.000Z',
    ownershipWindowStart: '2026-06-27T17:30:00.000Z',
    ownershipWindowEnd: '2026-06-29T17:30:00.000Z',
    consentTimestamp: '2026-06-27T17:25:00.000Z',
    sourceLeadId: 'lead-1',
    locked: false,
    updatedAt: '2026-06-27T17:30:00.000Z',
  },
  {
    id: 'ref-101',
    agencyId: 'agency-101',
    inquiryFor: 'Spouse',
    firstNameMasked: 'R***',
    lastNameMasked: 'T*****',
    fullNameEncrypted: 'Robert Tanaka',
    emailMasked: 'r***@example.com',
    phoneMasked: '(555) ***-**12',
    category: 'Memory Care',
    locationZip: '94107',
    message: 'Spouse with early-stage dementia, needs daytime support.',
    status: 'Contacted',
    assignmentDate: '2026-06-24T15:00:00.000Z',
    ownershipWindowStart: '2026-06-24T15:00:00.000Z',
    ownershipWindowEnd: '2026-06-26T15:00:00.000Z',
    consentTimestamp: '2026-06-24T14:50:00.000Z',
    sourceLeadId: 'lead-2',
    locked: false,
    updatedAt: '2026-06-25T19:12:00.000Z',
  },
  {
    id: 'ref-102',
    agencyId: 'agency-101',
    inquiryFor: 'Parent',
    firstNameMasked: 'E***',
    lastNameMasked: 'N******',
    fullNameEncrypted: 'Eleanor Nguyen',
    emailMasked: 'e***@example.com',
    phoneMasked: '(555) ***-**40',
    category: 'Companion Care',
    locationZip: '94110',
    message: 'Mother needs companionship and light housekeeping.',
    status: 'Assessment Scheduled',
    assignmentDate: '2026-06-20T16:45:00.000Z',
    ownershipWindowStart: '2026-06-20T16:45:00.000Z',
    ownershipWindowEnd: '2026-06-22T16:45:00.000Z',
    consentTimestamp: '2026-06-20T16:30:00.000Z',
    sourceLeadId: 'lead-3',
    locked: false,
    updatedAt: '2026-06-23T20:05:00.000Z',
  },
  {
    id: 'ref-103',
    agencyId: 'agency-101',
    inquiryFor: 'Myself',
    firstNameMasked: 'J***',
    lastNameMasked: 'P*****',
    fullNameEncrypted: 'James Park',
    emailMasked: 'j***@example.com',
    phoneMasked: '(555) ***-**88',
    category: 'Memory Care',
    locationZip: '94105',
    message: 'Recovering from surgery, needs overnight care for 2 weeks.',
    status: 'Start of Care',
    assignmentDate: '2026-06-10T14:00:00.000Z',
    ownershipWindowStart: '2026-06-10T14:00:00.000Z',
    ownershipWindowEnd: '2026-06-12T14:00:00.000Z',
    consentTimestamp: '2026-06-10T13:55:00.000Z',
    sourceLeadId: 'lead-4',
    locked: true,
    updatedAt: '2026-06-15T18:30:00.000Z',
  },
  {
    id: 'ref-104',
    agencyId: 'agency-101',
    inquiryFor: 'Other',
    firstNameMasked: 'C***',
    lastNameMasked: 'D*****',
    fullNameEncrypted: 'Carmen Diaz',
    emailMasked: 'c***@example.com',
    phoneMasked: '(555) ***-**05',
    category: 'Companion Care',
    locationZip: '94107',
    message: 'Neighbor inquiring on behalf of an elderly friend.',
    status: 'Declined',
    assignmentDate: '2026-06-05T11:20:00.000Z',
    ownershipWindowStart: '2026-06-05T11:20:00.000Z',
    ownershipWindowEnd: '2026-06-07T11:20:00.000Z',
    consentTimestamp: '2026-06-05T11:10:00.000Z',
    sourceLeadId: 'lead-5',
    locked: true,
    updatedAt: '2026-06-08T09:45:00.000Z',
  },
  {
    id: 'ref-105',
    agencyId: 'agency-101',
    inquiryFor: 'Parent',
    firstNameMasked: 'W***',
    lastNameMasked: 'O*****',
    fullNameEncrypted: 'Wei Okafor',
    emailMasked: 'w***@example.com',
    phoneMasked: '(555) ***-**73',
    category: 'Companion Care',
    locationZip: '94110',
    message: 'Looking for weekend coverage for my father.',
    status: 'New',
    assignmentDate: '2026-06-28T08:15:00.000Z',
    ownershipWindowStart: '2026-06-28T08:15:00.000Z',
    ownershipWindowEnd: '2026-06-30T08:15:00.000Z',
    consentTimestamp: '2026-06-28T08:05:00.000Z',
    sourceLeadId: 'lead-6',
    locked: false,
    updatedAt: '2026-06-28T08:15:00.000Z',
  },
  // Belongs to a DIFFERENT agency — must never appear in agency-101's views.
  {
    id: 'ref-200',
    agencyId: 'agency-202',
    inquiryFor: 'Spouse',
    firstNameMasked: 'A***',
    lastNameMasked: 'B*****',
    fullNameEncrypted: 'Amir Bello',
    emailMasked: 'a***@example.com',
    phoneMasked: '(555) ***-**31',
    category: 'Skilled Nursing',
    locationZip: '94601',
    message: 'Post-hospital skilled nursing needed.',
    status: 'Contacted',
    assignmentDate: '2026-06-26T10:00:00.000Z',
    ownershipWindowStart: '2026-06-26T10:00:00.000Z',
    ownershipWindowEnd: '2026-06-28T10:00:00.000Z',
    consentTimestamp: '2026-06-26T09:50:00.000Z',
    sourceLeadId: 'lead-7',
    locked: false,
    updatedAt: '2026-06-27T12:00:00.000Z',
  },
]

// ---- Referral outcome updates --------------------------------------------

export const mockOutcomeUpdates: ReferralOutcomeUpdate[] = [
  {
    id: 'upd-001',
    referralId: 'ref-101',
    agencyId: 'agency-101',
    outcome: 'Contacted',
    notes: 'Left voicemail and sent intro email. Awaiting callback.',
    dateOfUpdate: '2026-06-25T19:12:00.000Z',
    updatedBy: 'Sarah Intake',
    createdAt: '2026-06-25T19:12:00.000Z',
  },
  {
    id: 'upd-002',
    referralId: 'ref-102',
    agencyId: 'agency-101',
    outcome: 'Assessment Scheduled',
    notes: 'In-home assessment booked for next Tuesday at 10am.',
    dateOfUpdate: '2026-06-23T20:05:00.000Z',
    updatedBy: 'Sarah Intake',
    createdAt: '2026-06-23T20:05:00.000Z',
  },
  {
    id: 'upd-003',
    referralId: 'ref-103',
    agencyId: 'agency-101',
    outcome: 'Start of Care',
    notes: 'Care plan signed; caregiver assigned for overnight shifts.',
    dateOfUpdate: '2026-06-15T18:30:00.000Z',
    updatedBy: 'David Owner',
    createdAt: '2026-06-15T18:30:00.000Z',
  },
]

// ---- Revenue submissions --------------------------------------------------

export const mockRevenue: RevenueSubmission[] = [
  {
    id: 'rev-001',
    agencyId: 'agency-101',
    referralId: 'ref-103',
    monthYear: '2026-05',
    revenueAmount: 6200,
    paymentMode: 'Autopay',
    supportingNotes: 'Overnight care, 30 nights.',
    status: 'Submitted',
    submittedAt: '2026-06-02T15:00:00.000Z',
    submittedBy: 'Priya Billing',
  },
  {
    id: 'rev-002',
    agencyId: 'agency-101',
    referralId: 'ref-102',
    monthYear: '2026-05',
    revenueAmount: 3120,
    paymentMode: 'ACH',
    supportingNotes: 'Companion care, 24 hrs/week.',
    status: 'Submitted',
    submittedAt: '2026-06-02T15:10:00.000Z',
    submittedBy: 'Priya Billing',
  },
  {
    id: 'rev-003',
    agencyId: 'agency-101',
    referralId: 'ref-103',
    monthYear: '2026-06',
    revenueAmount: 0,
    paymentMode: 'Autopay',
    status: 'Draft',
  },
]

// ---- Support threads (chat) ----------------------------------------------

export const mockSupportThreads: SupportThread[] = [
  {
    id: 'thread-001',
    agencyId: 'agency-101',
    subject: 'How do I update a referral after it is locked?',
    category: 'Referrals',
    status: 'Open',
    createdBy: 'Sarah Intake',
    createdAt: '2026-06-27T16:00:00.000Z',
    updatedAt: '2026-06-27T16:08:00.000Z',
    messages: [
      {
        id: 'msg-001',
        author: 'Sarah Intake',
        authorRole: 'provider',
        body: 'Hi — one of my referrals shows as locked. How can I add a final note?',
        sentAt: '2026-06-27T16:00:00.000Z',
      },
      {
        id: 'msg-002',
        author: 'FindAHomeCare Support',
        authorRole: 'support',
        body: 'Locked referrals are read-only for providers once they reach a final status. An internal coordinator can reopen it if a correction is needed — want me to flag this one?',
        sentAt: '2026-06-27T16:05:00.000Z',
      },
      {
        id: 'msg-003',
        author: 'Sarah Intake',
        authorRole: 'provider',
        body: 'Yes please, the note is just a clarification on the start date.',
        sentAt: '2026-06-27T16:08:00.000Z',
      },
    ],
  },
  {
    id: 'thread-002',
    agencyId: 'agency-101',
    subject: 'Autopay revenue submission question',
    category: 'Billing',
    status: 'Resolved',
    createdBy: 'Priya Billing',
    createdAt: '2026-06-20T14:00:00.000Z',
    updatedAt: '2026-06-20T14:15:00.000Z',
    messages: [
      {
        id: 'msg-101',
        author: 'Priya Billing',
        authorRole: 'provider',
        body: 'For Autopay, do I still need to upload a proof of revenue document?',
        sentAt: '2026-06-20T14:00:00.000Z',
      },
      {
        id: 'msg-102',
        author: 'FindAHomeCare Support',
        authorRole: 'support',
        body: 'No — Autopay pulls directly from the monthly revenue fields, so no physical proof is required.',
        sentAt: '2026-06-20T14:15:00.000Z',
      },
    ],
  },
]

// ---- Audit events (seed history) -----------------------------------------

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'aud-seed-001',
    actorId: 'user-001',
    actorRole: 'Provider Intake Coordinator',
    agencyId: 'agency-101',
    action: 'referral_outcome_updated',
    objectType: 'Referral',
    objectId: 'ref-101',
    timestamp: '2026-06-25T19:12:00.000Z',
    ip: '203.0.113.24',
    userAgent: 'Mozilla/5.0 (prototype)',
    phiFlag: false,
    surface: 'provider',
    metadata: { outcome: 'Contacted' },
  },
  {
    id: 'aud-seed-002',
    actorId: 'user-002',
    actorRole: 'Provider Owner',
    agencyId: 'agency-101',
    action: 'referral_outcome_updated',
    objectType: 'Referral',
    objectId: 'ref-103',
    timestamp: '2026-06-15T18:30:00.000Z',
    ip: '203.0.113.24',
    userAgent: 'Mozilla/5.0 (prototype)',
    phiFlag: false,
    surface: 'provider',
    metadata: { outcome: 'Start of Care' },
  },
  {
    id: 'aud-seed-003',
    actorId: 'user-001',
    actorRole: 'Provider Intake Coordinator',
    agencyId: 'agency-101',
    action: 'verified_with_no_changes',
    objectType: 'Agency',
    objectId: 'agency-101',
    timestamp: '2026-05-30T16:20:00.000Z',
    ip: '203.0.113.24',
    userAgent: 'Mozilla/5.0 (prototype)',
    phiFlag: false,
    surface: 'provider',
  },
  {
    id: 'aud-seed-004',
    actorId: 'user-003',
    actorRole: 'Provider Billing',
    agencyId: 'agency-101',
    action: 'revenue_submitted',
    objectType: 'RevenueSubmission',
    objectId: 'rev-001',
    timestamp: '2026-06-02T15:00:00.000Z',
    ip: '203.0.113.51',
    userAgent: 'Mozilla/5.0 (prototype)',
    phiFlag: false,
    surface: 'provider',
    metadata: { monthYear: '2026-05', amount: 6200, paymentMode: 'Autopay' },
  },
]

// ---- Documents ------------------------------------------------------------

export const mockDocuments: DocumentFile[] = [
  {
    id: 'doc-001',
    agencyId: 'agency-101',
    driveFileId: 'drive-mock-001',
    driveFolderId: 'folder-mock-101',
    fileName: 'business-license-2026.pdf',
    mimeType: 'application/pdf',
    size: 248_000,
    category: 'License',
    uploadedBy: 'David Owner',
    uploadedAt: '2026-01-12T10:00:00.000Z',
    phiFlag: false,
    hash: 'sha256:9af1c0...mock',
  },
]
